### ISSUE TITLE
[PE-D][Tester A] I am able to add numbers to medication name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T15-2/tp#171]
`add mn/2 d/3`

Will result in 

![image.png](https://raw.githubusercontent.com/garylow2001/ped/main/files/0fa092b7-ea8b-4867-ab85-45d45dc015e8.png)

I believe that while medication names could contain numbers, it should not be a pure numerical string.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: garylow2001/ped#1

**Comment by ChongWeiJie29** [comment]
The intention behind this is to allow users to key in anything that best helps them associate this entry to their prescription. Hence, we would allow them to input a name like m2 as well, as long as it is useful for them. 

Furthermore, due to the constraints of the app being an offline, we are unable to do any form of checking to ensure that the inserted prescription is a valid prescription in a nationally recognised database. Perhaps it can be implemented as a possible future development
